package net.oldmanyounger.shroud.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.RegistrySetBuilder;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.DatapackBuiltinEntriesProvider;
import net.oldmanyounger.shroud.Shroud;
import net.oldmanyounger.shroud.trim.ModTrimMaterials;
import net.oldmanyounger.shroud.trim.ModTrimPatterns;
import net.oldmanyounger.shroud.worldgen.ModConfiguredFeatures;
import net.oldmanyounger.shroud.worldgen.ModPlacedFeatures;

import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * Generates built-in datapack registry entries for Shroud.
 *
 * <p>This provider is used for registry-backed datapack content that is defined
 * through bootstrap methods instead of handwritten static JSON alone. It wires
 * together trim materials, trim patterns, configured features, and placed
 * features so those registries can be generated into the mod's built-in datapack
 * output.
 *
 * <p>In the broader context of the project, this class acts as the bridge
 * between Shroud's Java bootstrap code and the generated registry data consumed
 * by Minecraft's datapack loading systems.
 */
public class ModDatapackProvider extends DatapackBuiltinEntriesProvider {

    // Registry builder containing all built-in datapack-backed registries generated by Shroud
    public static final RegistrySetBuilder BUILDER = new RegistrySetBuilder()
            .add(Registries.TRIM_MATERIAL, ModTrimMaterials::bootstrap)
            .add(Registries.TRIM_PATTERN, ModTrimPatterns::bootstrap)
            .add(Registries.CONFIGURED_FEATURE, ModConfiguredFeatures::bootstrap)
            .add(Registries.PLACED_FEATURE, ModPlacedFeatures::bootstrap);

    // Creates the datapack provider for the Shroud namespace
    public ModDatapackProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
        super(output, registries, BUILDER, Set.of(Shroud.MOD_ID));
    }
}